import { readState } from './storage.js';
let preferences={language:'de',timeFormat:'24'};
try{Object.assign(preferences,(await readState('product-v3'))?.profile||{});}catch{}
export const locale=()=>({de:'de-DE',en:'en-GB',fr:'fr-FR'}[preferences.language]||'de-DE');
export function clockLabel(value='07:00'){
 const [h,m]=value.split(':').map(Number),date=new Date(2026,0,1,h,m);
 return date.toLocaleTimeString(locale(),{hour:'2-digit',minute:'2-digit',hourCycle:preferences.timeFormat==='12'?'h12':'h23'});
}
export function setPreferences(profile){preferences={...preferences,...profile};document.documentElement.lang=preferences.language;translateUI(document.body);}
const entries=[
 ['Sammlung','Collection','Collection'],['Sortieren nach','Sort by','Trier par'],['Wochenplan aufheben','Remove weekly schedule','Supprimer le programme hebdomadaire'],['Stunden','Hours','Heures'],['Tageshälfte','AM or PM','Matin ou après-midi'],['Zurück zur Planung','Back to scheduling','Retour à la planification'],
 ['Merken','Save','Enregistrer'],['Gemerkt','Saved','Enregistrés'],['Selbst erstellt','Created by me','Mes créations'],['Eigene','My own','Mes créations'],
 ['Filter & Sortierung','Filter & sort','Filtrer et trier'],['Herkunft','Source','Origine'],['Sortierung','Sort order','Ordre de tri'],
 ['Ritual planen','Schedule ritual','Planifier le rituel'],['Einzelner Tag','Single day','Jour précis'],['Einzelne Termine','Individual dates','Dates précises'],['Datum','Date','Date'],
 ['Weiteren Tag planen','Schedule another day','Planifier un autre jour'],
 ['Symbol und Farbe ändern','Change symbol and colour','Modifier le symbole et la couleur'],
 ['Ein Ritual pro Tag','One ritual per day','Un rituel par jour'],
 ['Bei bisherigen Überschneidungen bleibt der früheste Termin. Einzelne Termine haben Vorrang vor dem Wochenplan. Deine Rituale und dein Verlauf bleiben erhalten.','For existing overlaps, the earliest appointment is kept. Dated appointments override the weekly schedule. Your rituals and history are preserved.','En cas de chevauchement, le premier rendez-vous est conservé. Les dates précises ont priorité sur le programme hebdomadaire. Vos rituels et votre historique sont conservés.'],
 ['Verstanden','Got it','Compris'],
 ['Ein Ritual pro Tag. Diese Auswahl gilt nur für diesen Morgen. Dein Wochenplan bleibt bestehen.','One ritual per day. This choice applies only to this morning. Your weekly schedule stays the same.','Un rituel par jour. Ce choix ne concerne que ce matin. Votre programme hebdomadaire reste inchangé.'],
 ['Ein Ritual pro Wochentag. Bereits belegte Tage kannst du beim Speichern übernehmen. Einzelne Datumstermine haben Vorrang.','One ritual per weekday. When saving, you can replace rituals on occupied days. Dated appointments take priority.','Un rituel par jour de la semaine. Vous pouvez remplacer les rituels des jours occupés lors de l’enregistrement. Les dates précises sont prioritaires.'],
 ['Für diesen Tag wurde bereits ein Ritual begonnen. Wähle einen anderen Tag.','A ritual has already been started on this day. Choose another day.','Un rituel a déjà été commencé ce jour-là. Choisissez un autre jour.'],
 ['Ritual für diesen Tag ersetzen?','Replace this day’s ritual?','Remplacer le rituel de ce jour ?'],
 ['Wochentage übernehmen?','Replace the weekly schedule?','Remplacer les jours du programme ?'],
 ['Ersetzen','Replace','Remplacer'],
 ['Dein Buddy liest den Inhalt vor.','Your buddy reads the content aloud.','Votre buddy lit le contenu à voix haute.'],
 ['Du liest den Inhalt selbst.','You read the content yourself.','Vous lisez le contenu vous-même.'],
 ['Ohne Recherche bleibt dein Text unverändert. Mit Recherche wird im jeweiligen Schritt das Ergebnis angezeigt oder vorgelesen.','Without research, your text stays unchanged. With research, that step displays or reads out the result.','Sans recherche, votre texte reste inchangé. Avec recherche, cette étape affiche ou lit le résultat.'],
 ['Dein Text wird unverändert angezeigt oder vorgelesen.','Your text is displayed or read aloud unchanged.','Votre texte est affiché ou lu sans modification.'],
 ['Dein Text ist der Rechercheauftrag. Verwendet wird das recherchierte Ergebnis.','Your text is the research request. The research result is used as the content.','Votre texte est la consigne de recherche. Le résultat constitue le contenu.'],
 ['Live-Recherche ist in diesem Prototyp noch nicht verbunden. Die Vorschau zeigt nur vorhandene Beispielergebnisse.','Live research is not connected in this prototype yet. The preview only shows existing sample results.','La recherche en direct n’est pas encore connectée dans ce prototype. L’aperçu affiche uniquement les exemples disponibles.'],
 ['Geplant','Scheduled','Planifié'],['Keine Rituale','No rituals','Aucun rituel'],
 ['Dunkelmodus','Dark mode','Mode sombre'],['Aus','Off','Désactivé'],['An','On','Activé'],['Automatisch','Automatic','Automatique'],['Dunkel von 19:00 bis 07:00 · Ortszeit','Dark from 19:00 to 07:00 · local time','Sombre de 19 h à 7 h · heure locale'],['Kopieren & bearbeiten','Copy & edit','Copier et modifier'],['Automatisches Cover','Automatic cover','Pochette automatique'],['Coverfoto ändern','Change cover photo','Modifier la pochette'],['Foto zuschneiden','Crop photo','Recadrer la photo'],['Bildausschnitt verschieben','Move crop','Déplacer le cadrage'],['Übernehmen','Apply','Appliquer'],['Maximal 10 Schritte pro Baustein.','Maximum 10 steps per block.','10 étapes maximum par bloc.'],['Maximal 10 Bausteine pro Ritual.','Maximum 10 blocks per routine.','10 blocs maximum par rituel.'],['Weitere Optionen','More options','Autres options'],['Dein Buddy','Your buddy','Votre buddy'],['Form','Shape','Forme'],['Form & Farbe','Shape & colour','Forme et couleur'],['Warm & fürsorglich','Warm & caring','Chaleureux et attentionné'],['Klar & motivierend','Clear & motivating','Clair et motivant'],['Verspielt & leicht','Playful & light','Joueur et léger'],['Gelassen & sanft','Calm & gentle','Calme et doux'],['Ruhig & strukturiert','Steady & structured','Posé et structuré'],['Neugierig & offen','Curious & open','Curieux et ouvert'],['Weibliche Stimme','Female voice','Voix féminine'],['Männliche Stimme','Male voice','Voix masculine'],['Hörproben nutzen verfügbare Systemstimmen. Je nach Browser können sich Buddies eine Grundstimme teilen.','Previews use available system voices. Depending on your browser, buddies may share a base voice.','Les aperçus utilisent les voix disponibles sur votre appareil. Selon le navigateur, des buddies peuvent partager une même voix.'],['Foto in Vollbild öffnen','Expand photo','Agrandir la photo'],['Vollbild schließen','Close full screen','Fermer le plein écran'],
 ['Home','Home','Accueil'],['Entdecken','Discover','Découvrir'],['Bibliothek','Library','Bibliothèque'],['Verlauf','History','Historique'],['Kalender','Calendar','Calendrier'],
 ['Ritual','Ritual','Rituel'],['Rituale','Rituals','Rituels'],['Baustein','Block','Bloc'],['Bausteine','Blocks','Blocs'],['Dein Morgen','Your morning','Votre matin'],
 ['Heute beginnt','Today begins','Aujourd’hui commence'],['mit','with','avec'],['dir.','you.','vous.'],['DEIN MOMENT AM MORGEN','YOUR MORNING MOMENT','VOTRE MOMENT DU MATIN'],
 ['Dein Morgen wartet','Your morning is waiting','Votre matin vous attend'],['Dein Morgen ist noch da','There’s still time for your morning','Il est encore temps pour votre rituel'],['Zeit für dich genommen','You made time for yourself','Vous avez pris du temps pour vous'],['Dein nächster Morgen','Your next morning','Votre prochain matin'],['Dein Morgen beginnt hier','Your morning starts here','Votre matin commence ici'],
 ['Dein heutiges Ritual ist durchgeführt.','Your ritual for today is complete.','Votre rituel du jour est terminé.'],['Deine Rituale','Your rituals','Vos rituels'],['Alle ansehen','See all','Tout voir'],['Los geht’s','Let’s go','C’est parti'],['Fortsetzen','Resume','Reprendre'],['Ein Ritual auswählen','Choose a ritual','Choisir un rituel'],
 ['Bausteine und Rituale suchen','Search blocks and rituals','Rechercher des blocs et des rituels'],['In deiner Bibliothek suchen','Search your library','Rechercher dans votre bibliothèque'],['Alle','All','Tous'],['Filter','Filters','Filtres'],['Featured','Featured','À la une'],['Mehr entdecken','Explore more','Explorer davantage'],['Keine Treffer.','No results.','Aucun résultat.'],['Versuche andere Tags oder einen anderen Suchbegriff.','Try another tag or search term.','Essayez un autre thème ou terme.'],['Filter zurücksetzen','Reset filters','Réinitialiser les filtres'],['Zuletzt hinzugefügt','Recently added','Ajoutés récemment'],
 ['Dein Ablauf','Your sequence','Votre déroulement'],['Bearbeiten','Edit','Modifier'],['Fertig','Done','Terminé'],['Baustein hinzufügen','Add a block','Ajouter un bloc'],['Zu Ritual hinzufügen','Add to rituals','Ajouter aux rituels'],['In deinen Ritualen','In your rituals','Dans vos rituels'],['In deiner Bibliothek','In your library','Dans votre bibliothèque'],['In Bibliothek speichern','Save to library','Enregistrer dans la bibliothèque'],['Baustein bearbeiten','Edit block','Modifier le bloc'],['Aus Bibliothek entfernen','Remove from library','Retirer de la bibliothèque'],['Vorschau','Preview','Aperçu'],['Morgen-Vorschau','Morning preview','Aperçu du matin'],['Zurück','Back','Retour'],['Speichern','Save','Enregistrer'],['Neu','New','Nouveau'],['Neues Ritual','New ritual','Nouveau rituel'],['Ritual bearbeiten','Edit ritual','Modifier le rituel'],['Titel des Rituals','Ritual title','Titre du rituel'],['Beschreibung (optional)','Description (optional)','Description (facultative)'],['Wie möchtest du in den Tag starten?','How would you like to start your day?','Comment souhaitez-vous commencer la journée ?'],['Ritual erstellen','Create ritual','Créer le rituel'],['Ritual löschen','Delete ritual','Supprimer le rituel'],['Eigenen Baustein erstellen','Create your own block','Créer votre propre bloc'],['Bereits enthalten','Already added','Déjà ajouté'],['Entfernen','Remove','Retirer'],['Hinzufügen','Add','Ajouter'],
 ['Baustein erstellen','Create a block','Créer un bloc'],['Inhalt','Content','Contenu'],['Ausgabe','Output','Sortie'],['Titel des Bausteins','Block title','Titre du bloc'],['Worum geht’s?','What’s it about?','De quoi s’agit-il ?'],['Symbol & Farbe','Symbol & colour','Symbole et couleur'],['Beschreibung des Bausteins','Block description','Description du bloc'],['optional','optional','facultatif'],['Was macht deinen Baustein aus?','What makes your block special?','Qu’est-ce qui caractérise votre bloc ?'],['Tags','Tags','Thèmes'],['Anweisung','Instruction','Consigne'],['Rechercheauftrag','Research request','Demande de recherche'],['Was soll in diesem Schritt passieren?','What should happen in this step?','Que doit-il se passer à cette étape ?'],['Was soll der Buddy recherchieren?','What should Buddy research?','Que doit rechercher Buddy ?'],['Im Internet recherchieren','Search the web','Rechercher sur Internet'],['Deine Eingabe morgens','Your morning response','Votre réponse le matin'],['Keine','None','Aucune'],['Textfeld','Text field','Champ de texte'],['Memo','Voice note','Note vocale'],['Foto','Photo','Photo'],['Dauer','Duration','Durée'],['Automatisch weiter nach Ablauf','Advance when time is up','Avancer à la fin du temps prévu'],['Schritt hinzufügen','Add a step','Ajouter une étape'],['Weiter','Continue','Continuer'],['Ausgabe für alle Schritte','Output for every step','Sortie pour toutes les étapes'],['Audio','Audio','Audio'],['Text','Text','Texte'],['Original','Original','Original'],['Deine Anleitung, gesprochen.','Your instructions, spoken.','Vos consignes, à voix haute.'],['Deine Anleitung, als Text.','Your instructions, as text.','Vos consignes, sous forme de texte.'],['Deine eigene Anweisung, unverändert.','Your own instruction, unchanged.','Votre propre consigne, inchangée.'],['Nicht verfügbar','Unavailable','Indisponible'],['Recherche benötigt Audio oder Text.','Research requires audio or text.','La recherche nécessite une sortie audio ou texte.'],['Recherche benötigt Audio oder Text. Bitte ändere die Ausgabe.','Research requires audio or text. Please change the output.','La recherche nécessite une sortie audio ou texte. Modifiez la sortie.'],['Hintergrundmusik','Background music','Musique de fond'],['Keine Musik','No music','Sans musique'],['Wähle eine Ausgabe für deinen Baustein.','Choose an output for your block.','Choisissez une sortie pour votre bloc.'],['Dein Soundtrack','Your soundtrack','Votre bande-son'],['Nur dein Moment','Just your moment','Rien que votre moment'],['Sanfte Glocken · ruhig','Soft bells · calm','Cloches douces · calme'],['Warme Töne · konzentriert','Warm tones · focused','Tons chaleureux · concentration'],['Leichter Rhythmus · wach','Light rhythm · awake','Rythme léger · éveil'],['Dein Look','Your look','Votre style'],['Symbol','Symbol','Symbole'],['Farbe','Colour','Couleur'],
 ['Deine Gedanken …','Your thoughts …','Vos pensées…'],['Deine Antwort','Your response','Votre réponse'],['Memo aufnehmen','Record a voice note','Enregistrer une note vocale'],['Aufnahme beenden','Stop recording','Arrêter l’enregistrement'],['Deine Gedanken, in deiner Stimme.','Your thoughts, in your own voice.','Vos pensées, avec votre voix.'],['Foto hinzufügen','Add a photo','Ajouter une photo'],['Foto wechseln','Change photo','Changer de photo'],['Überspringen','Skip','Passer'],['In deinem Tempo','At your own pace','À votre rythme'],['Pausiert','Paused','En pause'],['Pausieren','Pause','Mettre en pause'],['Deine Antwort hat Zeit.','Take your time to respond.','Prenez le temps de répondre.'],['Kurz durchatmen.','Take a breath.','Respirez un instant.'],['Zurück zum Editor','Back to editor','Retour à l’éditeur'],['Zurück zur Übersicht','Back to overview','Retour à la vue d’ensemble'],['Zurück zu Home','Back to Home','Retour à l’accueil'],['Hallo Tag.','Hello, day.','Bonjour, journée.'],['Ich bin da.','I’m here.','Je suis là.'],['DIESER MOMENT GEHÖRT DIR','THIS MOMENT IS YOURS','CE MOMENT VOUS APPARTIENT'],['DEINE VORSCHAU','YOUR PREVIEW','VOTRE APERÇU'],['So beginnt','This is how','C’est ainsi que commence'],['dein Morgen.','your morning begins.','votre matin.'],['Deine Einstellungen sind bereit.','Your settings are ready.','Vos réglages sont prêts.'],['Nimm dieses Gefühl mit in deinen Tag.','Take this feeling into your day.','Gardez cette sensation pour la journée.'],['Dieser Durchlauf wurde ausgelassen.','This session was skipped.','Cette séance a été passée.'],
 ['Deine Morgen.','Your mornings.','Vos matins.'],['Deine letzten 12 Wochen','Your last 12 weeks','Vos 12 dernières semaines'],['Durchgeführt','Completed','Terminé'],['Unterbrochen','Interrupted','Interrompu'],['Ausgelassen','Skipped','Passé'],['Unterbrochen / ausgelassen','Interrupted / skipped','Interrompu / passé'],['Abgeschlossen','Completed','Terminé'],['Übersprungen','Skipped','Passé'],['Offen','Not completed','Non terminé'],['Keine Antwort hinterlegt.','No response recorded.','Aucune réponse enregistrée.'],['Deine Anweisung','Your instruction','Votre consigne'],['Hier beginnt deine Geschichte.','Your story starts here.','Votre histoire commence ici.'],['Nach deinem ersten Ritual findest du hier deinen Durchlauf und deine Antworten.','After your first ritual, your session and responses will appear here.','Après votre premier rituel, vous retrouverez ici votre séance et vos réponses.'],['Zu deinen Ritualen','Go to your rituals','Accéder à vos rituels'],['Ein Moment nach dem anderen.','One moment at a time.','Un moment après l’autre.'],
 ['Heute','Today','Aujourd’hui'],['Ein Morgen nach dem anderen.','One morning at a time.','Un matin après l’autre.'],['Wöchentlich','Weekly','Chaque semaine'],['Nur an diesem Tag','Only on this day','Uniquement ce jour-là'],['Ritual einplanen','Schedule a ritual','Planifier un rituel'],['Zeit für einen freien Morgen.','Room for a free morning.','Place à un matin libre.'],['Für diesen Tag ändern','Change for this day','Modifier pour ce jour'],['Ritual öffnen','Open ritual','Ouvrir le rituel'],['Ritual auswählen','Choose a ritual','Choisir un rituel'],['Deine Rituale durchsuchen','Search your rituals','Rechercher vos rituels'],['Weckzeit','Alarm time','Heure du réveil'],['Nur für diesen Morgen. Dein Wochenplan bleibt bestehen.','Only for this morning. Your weekly schedule stays the same.','Pour ce matin uniquement. Votre programme hebdomadaire reste inchangé.'],['Einplanen','Schedule','Planifier'],['Ausnahme entfernen','Remove exception','Supprimer l’exception'],['Dein Wecker','Your alarm','Votre réveil'],['Aktiv','Enabled','Activé'],['Weckton','Alarm sound','Sonnerie du réveil'],['Weckzeit einstellen','Set an alarm','Régler le réveil'],['Noch kein Wecker','No alarm yet','Aucun réveil défini'],['Jeden Tag','Every day','Tous les jours'],['Keine Tage','No days','Aucun jour'],['Kalender öffnen','Open calendar','Ouvrir le calendrier'],
 ['Dein Profil','Your profile','Votre profil'],['Dein Name','Your name','Votre nom'],['Profilbild ändern','Change profile photo','Changer la photo de profil'],['Einstellungen','Settings','Réglages'],['Sprache','Language','Langue'],['Zeitformat','Time format','Format de l’heure'],['24 Stunden','24 hours','24 heures'],['12 Stunden','12 hours','12 heures'],['Support','Support','Assistance'],['Wecker ausprobieren','Try the alarm','Essayer le réveil'],['Testbereich','Test area','Espace de test'],['Gespeichert.','Saved.','Enregistré.'],['Schließen','Close','Fermer'],['Profil schließen','Close profile','Fermer le profil'],['Aufwachen ausprobieren','Try waking up','Essayer le réveil'],['Geführter Demo-Morgen','Guided sample morning','Matin de démonstration guidé'],['Alle vier Eingabearten erleben','Try all four response types','Essayer les quatre types de réponse'],['Lockscreen, Weckton und dein Morgen – einmal durchspielen.','Try the lock screen, alarm and your morning flow.','Essayez l’écran verrouillé, le réveil et votre rituel.'],['Wecker-Demo','Alarm preview','Aperçu du réveil'],['Guten Morgen.','Good morning.','Bonjour.'],['Dein Moment','Your moment','Votre moment'],['beginnt jetzt.','starts now.','commence maintenant.'],['Ich bin wach','I’m awake','Je suis réveillé'],['Hallo, du.','Hello, you.','Bonjour, vous.'],['Dein Ritual wartet schon.','Your ritual is waiting.','Votre rituel vous attend.'],['Zum Entsperren nach oben wischen','Swipe up to unlock','Balayez vers le haut pour déverrouiller'],['Dein Morgen steht bereit.','Your morning is ready.','Votre matin est prêt.'],['Simulation startet gleich mit Ton.','The preview will start with sound.','L’aperçu va commencer avec le son.'],
 ['Bitte wähle ein Foto bis 20 MB.','Choose a photo up to 20 MB.','Choisissez une photo de 20 Mo maximum.'],['Bitte wähle eine Bilddatei.','Choose an image file.','Choisissez une image.'],['Dieses Foto kann dein Browser nicht lesen. Bitte verwende JPG, PNG oder WebP.','Your browser cannot read this photo. Use JPG, PNG or WebP.','Votre navigateur ne peut pas lire cette photo. Utilisez JPG, PNG ou WebP.'],['Erlaube den Mikrofonzugriff oder überspringe diesen Schritt.','Allow microphone access or skip this step.','Autorisez le microphone ou passez cette étape.'],['Kein passendes Ritual.','No matching ritual.','Aucun rituel correspondant.']
];
entries.push(
 ['Bausteine auswählen','Choose blocks','Choisir des blocs'],['Morgen','Tomorrow','Demain'],['Noch kein Ritual geplant.','No ritual planned yet.','Aucun rituel prévu.'],['Ritual für morgen auswählen','Choose a ritual for tomorrow','Choisir un rituel pour demain'],['Ritual für morgen','Ritual for tomorrow','Rituel pour demain'],['Begonnen','Started','Commencé'],['Löschaktion anzeigen','Show delete action','Afficher la suppression'],['Baustein löschen?','Delete block?','Supprimer le bloc ?'],['Dieser Baustein wird zusätzlich auch aus allen bestehenden Ritualen entfernt.','This block will also be removed from all existing rituals.','Ce bloc sera également retiré de tous les rituels existants.'],['Baustein gelöscht.','Block deleted.','Bloc supprimé.'],['Ritual gelöscht.','Ritual deleted.','Rituel supprimé.'],['Termin entfernt.','Scheduled ritual removed.','Rituel déplanifié.'],['Wiederhergestellt.','Restored.','Restauré.'],['Ritual-Cover','Ritual cover','Couverture du rituel'],['Foto ändern','Change photo','Changer la photo'],['Durchlauf ansehen','View session','Voir la séance']
);
entries.push(
 ['Text','Text','Texte'],['Reihenfolge ändern','Change order','Modifier l’ordre'],['Sortieren','Sort','Trier'],
 ['Teilweise durchgeführt','Partially completed','Partiellement effectué'],['Termin entfernen','Remove appointment','Retirer de ce jour'],
 ['Verlauf ansehen','View history','Voir l’historique'],['Entwürfe fortsetzen','Continue drafts','Reprendre les brouillons'],['Entwürfe','Drafts','Brouillons'],['Ohne Titel','Untitled','Sans titre'],
 ['Bausteine suchen','Search blocks','Rechercher des blocs'],['In Bibliothek öffnen','Open in library','Ouvrir dans la bibliothèque'],
 ['Durchlauf sichern','Export session','Exporter la séance'],['Durchlauf löschen','Delete session','Supprimer la séance'],['Durchlauf löschen?','Delete session?','Supprimer la séance ?'],
 ['Die Antworten dieses Durchlaufs werden gelöscht. Dein Ritual und dein Wochenplan bleiben erhalten.','This session’s answers will be deleted. Your routine and weekly schedule will remain.','Les réponses de cette séance seront supprimées. Votre rituel et votre programme hebdomadaire seront conservés.'],
 ['Änderungen gelten in allen Ritualen, die diesen Baustein verwenden.','Changes apply to every routine using this block.','Les modifications s’appliquent à tous les rituels utilisant ce bloc.'],
 ['Zurück zur Übersicht','Back to overview','Retour à l’aperçu'],['Nach Ablauf automatisch weiter','Continue automatically when time is up','Continuer automatiquement à la fin du temps'],['Nach Ablauf auf deine Antwort warten','Wait for your answer when time is up','Attendre votre réponse à la fin du temps'],
 ['Für diesen Tag liegen keine Planungsdaten vor.','No schedule information is available for this day.','Aucune donnée de planification pour ce jour.'],
 ['Kein regelmäßiger Weckplan','No weekly alarm schedule','Aucun réveil régulier'],['Wochenplan','Weekly schedule','Programme hebdomadaire'],['Tagesausnahme','One-day change','Exception pour ce jour'],
 ['Erstelle zuerst ein Ritual.','Create a routine first.','Créez d’abord un rituel.'],['Füge Bausteine hinzu, um dieses Ritual zu nutzen. Der Weckplan ist deaktiviert.','Add blocks to use this routine. Its alarm schedule is disabled.','Ajoutez des blocs pour utiliser ce rituel. Son réveil est désactivé.'],
 ['Erneut versuchen','Try again','Réessayer'],['Entwurf sichern','Export draft','Exporter le brouillon'],
 ['Speichern nicht möglich. Lass diese Seite geöffnet und versuche es erneut.','Could not save. Keep this page open and try again.','Enregistrement impossible. Gardez cette page ouverte et réessayez.'],
 ['Der Baustein konnte nicht gespeichert werden. Deine Eingaben bleiben hier. Bitte erneut versuchen.','Could not save the block. Your input remains here. Please try again.','Impossible d’enregistrer le bloc. Vos saisies restent ici. Veuillez réessayer.']
);
entries.push(
 ['Entwurf verwerfen','Discard draft','Abandonner le brouillon'],['Entwurf verwerfen?','Discard draft?','Abandonner le brouillon ?'],['Verwerfen','Discard','Abandonner'],
 ['Titel, Beschreibung und Auswahl dieses Entwurfs werden entfernt.','The title, description and selection in this draft will be removed.','Le titre, la description et la sélection de ce brouillon seront supprimés.'],
 ['Entwurf konnte nicht gespeichert werden.','Could not save draft.','Impossible d’enregistrer le brouillon.'],
 ['Rechts tippen: weiter. Links: neu starten.','Tap right: next. Tap left: restart.','Touchez à droite : suivant. À gauche : recommencer.'],['Noch einmal links: zurück.','Tap left again: previous.','Encore à gauche : précédent.'],['Hinweis schließen','Dismiss hint','Fermer le conseil']
);
entries.push(
 ['Alle löschen','Delete all','Tout supprimer'],['Keine Entwürfe.','No drafts.','Aucun brouillon.'],['Entwurf löschen','Delete draft','Supprimer le brouillon'],['Entwurf gelöscht.','Draft deleted.','Brouillon supprimé.'],['Entwürfe gelöscht.','Drafts deleted.','Brouillons supprimés.'],['Rückgängig','Undo','Annuler'],['Öffnen','Open','Ouvrir'],['Zur Bibliothek hinzufügen','Add to library','Ajouter à la bibliothèque'],['In deiner Bibliothek gespeichert.','Saved to your library.','Enregistré dans votre bibliothèque.'],['Ritual ersetzen','Replace ritual','Remplacer le rituel'],['Änderung speichern','Save change','Enregistrer la modification'],['Wochentage übernehmen','Replace weekdays','Remplacer les jours'],['Bereits geplant:','Already planned:','Déjà prévu :'],['Pro Tag ist ein Ritual möglich.','One ritual is possible per day.','Un rituel est possible par jour.']
);
const dictionary=new Map(entries.map(([de,en,fr])=>[de,{en,fr}]));
dictionary.set('Baustein aus Ritual entfernt.',{en:'Block removed from ritual.',fr:'Bloc retiré du rituel.'});
dictionary.set('Datum wählen',{en:'Choose date',fr:'Choisir une date'});
dictionary.set('Gib deinem Baustein einen Titel.',{en:'Give your block a title.',fr:'Donnez un titre à votre bloc.'});
export function t(text){
 if(preferences.language==='de')return text;const lang=preferences.language,trim=text.trim(),direct=dictionary.get(trim)?.[lang];
 if(direct)return text.replace(trim,direct);
 if(trim.endsWith(' begrüßen'))return text.replace(trim,lang==='en'?'Say hello to '+trim.slice(0,-9):'Dire bonjour à '+trim.slice(0,-9));
 if(trim.endsWith(' freut sich, dich zu sehen.'))return text.replace(' freut sich, dich zu sehen.',lang==='en'?' is happy to see you.':' est heureux de vous voir.');
 if(trim.endsWith(' aus Ritual entfernen'))return text.replace(' aus Ritual entfernen',lang==='en'?' — remove from ritual':' — retirer du rituel');
 if(trim.includes(' · '))return text.split(' · ').map(part=>t(part)).join(' · ');
 if(trim.startsWith('Von '))return text.replace('Von ',lang==='en'?'By ':'Par ');
 const draftCount=trim.match(/^(\d+) Entwürfe$/);if(draftCount)return text.replace(trim,draftCount[1]+(lang==='en'?' drafts':' brouillons'));
 if(trim.startsWith('Bereits belegt: '))return text.replace('Bereits belegt: ',lang==='en'?'Already occupied: ':'Déjà occupés : ').replace('. Ein Ritual pro Tag. Beim Speichern werden diese Tage nach Bestätigung übernommen.',lang==='en'?'. One ritual per day. Saving replaces these days after confirmation.':'. Un rituel par jour. Ces jours seront remplacés après confirmation.');
 const selection=trim.match(/^(\d+) \/ (\d+) ausgewählt$/);
 if(selection)return lang==='en'?`${selection[1]} / ${selection[2]} selected`:`${selection[1]} / ${selection[2]} sélectionnés`;
 const completion=trim.match(/^(\d+) von (\d+) Schritte abgeschlossen$/);
 if(completion)return lang==='en'?`${completion[1]} of ${completion[2]} steps completed`:`${completion[1]} étapes sur ${completion[2]} terminées`;
 const schedule=trim.match(/^(Wöchentlich|Nur an diesem Tag) · (\d+) Min\.$/);
 if(schedule)return `${t(schedule[1])} · ${schedule[2]} min`;
 const patterns=[[/^Schritt (\d+) von (\d+)$/,(a,b)=>lang==='en'?`Step ${a} of ${b}`:`Étape ${a} sur ${b}`],[/^Schritt (\d+)$/,(a)=>lang==='en'?`Step ${a}`:`Étape ${a}`],[/^(\d+) von (\d+) Bausteinen$/,(a,b)=>lang==='en'?`${a} of ${b} blocks`:`${a} blocs sur ${b}`],[/^(\d+) geplante Morgen in Folge$/,(a)=>lang==='en'?`${a} planned mornings in a row`:`${a} matins planifiés consécutifs`]];
 for(const [regex,format]of patterns){const m=trim.match(regex);if(m)return text.replace(trim,format(...m.slice(1)));}
 if(/^\d+[\s\S]*(Minuten|Min\.|Schritte|Bausteine|ausgewählt|abgeschlossen)/.test(trim))return text.replace(/Bausteine/g,lang==='en'?'blocks':'blocs').replace(/Schritte/g,lang==='en'?'steps':'étapes').replace(/Minuten/g,lang==='en'?'minutes':'minutes').replace(/Min\./g,'min').replace(/abgeschlossen/g,lang==='en'?'completed':'terminées').replace(/ausgewählt/g,lang==='en'?'selected':'sélectionnés');
 return text;
}
const originals=new WeakMap(),attributes=new WeakMap();
const protectedContent='[data-user-content],.formatted-text,.rich-input,[contenteditable],.playlist-copy strong,.catalog-copy b,.library-block b,.next-ritual strong,.track-open b,.ritual-hero h1,.ritual-hero>p,.detail-hero h1,.block-description,.story-owner b,.look-preview>span,.history-card b,.history-answer h3,.output-header h1,.preview-launch-card h1,.lock-ritual,.tag-picker,.tag-pills,.active-tags';
export function translateUI(root=document.body){
 if(!root)return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node;
 while(node=walker.nextNode()){
  const parent=node.parentElement;if(!parent||parent.closest('script,style,svg,textarea,option,'+protectedContent)||!node.textContent.trim())continue;
  const cached=originals.get(node),original=cached&&node.textContent===cached.translated?cached.original:node.textContent,translated=t(original);
  originals.set(node,{original,translated});if(node.textContent!==translated)node.textContent=translated;
 }
 root.querySelectorAll('[placeholder],[aria-label],option').forEach(el=>{
  for(const attr of ['placeholder','aria-label']){const value=el.getAttribute(attr);if(!value)continue;const cache=attributes.get(el)||{},prev=cache[attr],original=prev&&prev.translated===value?prev.original:value,translated=t(original);cache[attr]={original,translated};attributes.set(el,cache);if(value!==translated)el.setAttribute(attr,translated);}
 });
 document.documentElement.lang=preferences.language;
}
let pending=false;
new MutationObserver(()=>{if(!pending){pending=true;queueMicrotask(()=>{pending=false;translateUI();});}}).observe(document.body,{subtree:true,childList:true,characterData:true});
translateUI();
