import {enrichExperiences} from './team-experiences.js';
export const TEAM_PUBLISHER='wakeup-buddy-team';
export const isTeamOriginal=item=>item?.publisherId===TEAM_PUBLISHER&&!item.customized;
const s=(text,minutes=1,input='none',timer=false,research=false)=>({message:{type:'text',text},minutes,input,timer,research});
const b=(slug,title,description,tags,symbol,theme,output,steps,music='none')=>({id:'wb-'+slug,sourceId:'wb-'+slug,version:1,kind:'block',publisherId:TEAM_PUBLISHER,author:'Wakeup Buddy Team',title,description,tags,symbol,shape:'I',theme,output,steps:steps.map((s,i)=>({...s,id:'wb-'+slug+'-'+(i+1)})),music,musicVolume:.18});
const foundationBlocks=[
 b('boot','System hochfahren','Erst den Körper einchecken. Dann den Beast Mode suchen.',['Fitness','Personal Care'],'sun','sunny','buddy',[
 s('*Kurz die Lage checken*\n\nStell beide Füße auf den Boden. Wie wach bist du gerade von 1 bis 10? Wie fühlen sich Beine, Rücken und Schultern an? Heute musst du keinen Rekord beweisen. Bei Schmerzen lässt du die betreffende Bewegung aus.\n\nEntscheide dich für eine Intensität: locker, mittel oder heute nur mobilisieren.'),
 s('*Motor an, Ego aus*\n\nGehe 30 Sekunden locker auf der Stelle. Lass die Arme mitpendeln. Kreise danach fünfmal langsam die Schultern nach hinten und schüttle Hände und Beine aus. Wiederhole bis zum Signal.\n\nIm Sitzen: Hebe abwechselnd die Fersen und bewege die Schultern. Du bestimmst den Bewegungsumfang.',1,'none',true)],'flow'),
 b('mobility','Gelenke aufwecken','Drei Minuten Mobilität. Dein Schreibtischrücken darf mitmachen.',['Fitness','Personal Care'],'wave','sky','buddy',[
 s('*Oben locker werden*\n\nSteh bequem oder setz dich aufrecht hin. Zieh die Schultern fünfmal sanft hoch und lass sie wieder sinken. Dreh anschließend den Oberkörper langsam nach links und rechts, je fünfmal. Der Blick folgt mit.\n\nBleib in einem angenehmen Bereich. Kein Reißen, kein Nachdrücken.',1,'none',true),
 s('*Unten mitnehmen*\n\nHalte dich bei Bedarf an einer stabilen Stuhllehne fest. Rolle zehnmal von den Fersen auf die Fußballen. Hebe danach abwechselnd ein Knie ein kleines Stück an, zehnmal pro Seite. Wiederhole ruhig.\n\nIm Sitzen: Kreise die Fußgelenke und strecke abwechselnd ein Bein. Kleine Bewegungen zählen.',2,'none',true)],'flow'),
 b('technique','Technik vor Ego','Saubere Wiederholungen statt einer imaginären Kamera im Gym.',['Fitness'],'fitness','red','buddy',[
 s('*Sechs saubere Wiederholungen*\n\nStell dich vor einen stabilen Stuhl. Füße ungefähr hüftbreit, Knie folgen der Richtung der Zehen. Setz dich langsam hin und steh kontrolliert auf. Mach sechs Wiederholungen.\n\nNutze die Hände als Hilfe oder bleib sitzen und strecke abwechselnd ein Bein. Stoppe, wenn etwas schmerzt.',1,'none',true),
 s('*Noch eine Runde, ohne Eile*\n\nPause kurz. Wiederhole deine Variante sechsmal. Achte auf festen Stand und ruhige Bewegung, nicht auf Tiefe oder Tempo.\n\nDein Check am Ende: War die letzte Wiederholung so kontrolliert wie die erste? Wenn nicht, war die kleinere Variante heute die bessere.',1,'none',true)]),
 b('training','Training steht','Aus „irgendwann Sport“ wird ein Termin mit Plan B.',['Fitness','Getting things done'],'target','tangerine','text',[
 s('*Mach es konkret*\n\nNotiere drei Dinge:\n- Wann bewegst du dich heute?\n- Wo und womit?\n- Was genau machst du zuerst?\n\nZum Beispiel: 18 Uhr, Wohnzimmer, Matte ausrollen und mein gewohntes Training beginnen. Plane passend zu deinem heutigen Energielevel.',1,'text'),
 s('*Dein Plan B*\n\nWenn der Tag dazwischenkommt: Was ist deine kleine Alternative? Etwa zehn Minuten spazieren oder die Mobilitätsrunde wiederholen. Lege jetzt ein benötigtes Teil bereit.\n\nErgänze deinen Plan: „Wenn ___ nicht klappt, mache ich ___.“',1,'text')]),
 b('brain-dump','Kopf auskippen','Dein Kopf ist kein Browser mit 47 offenen Tabs.',['Mindfulness'],'wind','lilac','text',[
 s('*Alles darf raus*\n\nSchreib zwei Minuten ungefiltert auf, was gerade Platz im Kopf belegt. Aufgaben, Gefühle, halbe Gedanken. Kein schöner Text, keine Lösungspflicht.\n\nWenn du festhängst, beginne mit: „Gerade denke ich an …“ Lass Namen und private Details weg, wenn du sie nicht speichern möchtest.',2,'text'),
 s('*Einen Tab schließen*\n\nLies deine Notiz kurz. Welche Sache kannst du heute beeinflussen? Ergänze genau einen kleinen nächsten Schritt. Was gerade nicht lösbar ist, darf als offene Frage stehen bleiben.',1,'text')],'focus'),
 b('ground','Boden unter dir','Weniger Gedankenkino, mehr hier und jetzt.',['Mindfulness','Personal Care'],'leaf','sage','buddy',[
 s('*Hier bist du*\n\nSpüre den Boden unter deinen Füßen oder die Sitzfläche unter dir. Schau dich in Ruhe um. Benenne innerlich fünf Dinge, die du siehst, und drei Geräusche, die du hörst.\n\nFalls du wenig hörst: Welche Farben und Formen fallen dir auf? Es gibt nichts richtig zu machen.'),
 s('*Ein Detail reicht*\n\nWähle einen Gegenstand in deiner Nähe. Betrachte seine Kanten, Oberfläche und Farbe. Spüre danach wieder den Kontakt deiner Füße zum Boden. Atme so, wie es für dich angenehm ist.\n\nDu musst jetzt nicht entspannt sein. Es reicht, diesen Moment wahrzunehmen.')],'sunrise'),
 b('pressure','Druck rausnehmen','Ansprüche dürfen ambitioniert sein. Unmöglich müssen sie nicht sein.',['Mindfulness','Getting things done'],'heart','rose','text',[
 s('*Erwisch den Muss-Satz*\n\nWelcher Satz macht dir heute Druck? Schreib ihn auf: „Ich muss …“\n\nPrüfe danach: Was davon ist eine echte Verpflichtung, was eine Erwartung an dich selbst? Formuliere eine machbare Version. Aus „Ich muss alles schaffen“ könnte „Ich erledige heute die wichtige Rückmeldung“ werden.',2,'text')]),
 b('good-move','Ein guter Move','Ein kleiner Schritt, der auf deiner Seite steht.',['Mindfulness','Personal Care'],'compass','teal','text',[
 s('*Was würde helfen?*\n\nWähle eine kleine freundliche Handlung für dich: kurz ans Fenster, eine Pause eintragen, Hilfe erfragen oder etwas Belastendes für später notieren.\n\nSchreib: „Als Nächstes mache ich …“ und führe die Handlung aus, soweit sie jetzt möglich ist. Heute reicht ein guter Move.',2,'text')]),
 b('autopilot','Kein Autopilot','Bevor andere deinen Tag befüllen, setzt du die Richtung.',['Getting things done'],'compass','ocean','text',[
 s('*Heute Abend, kurz zurückgespult*\n\nStell dir vor, der Tag ist vorbei. Woran würdest du merken, dass du etwas Wichtiges vorangebracht hast?\n\nNotiere ein sichtbares Ergebnis statt eines Gefühls. „Eine Seite fertig“ ist greifbarer als „produktiv gewesen“. Es darf klein sein.',2,'text')]),
 b('priority','Eine Sache zählt','Priorität heißt: Du entscheidest, was zuerst dran ist.',['Getting things done'],'target','raspberry','text',[
 s('*Wähle deinen Hauptmove*\n\nSchreib höchstens drei Dinge auf, die heute anstehen. Markiere die eine Sache, deren Erledigung am meisten Unterschied macht.\n\nFormuliere ihren nächsten Schritt mit einem Verb: öffnen, skizzieren, anrufen, rechnen. Wenn du noch überlegen musst, was damit gemeint ist, mach ihn kleiner.',2,'text')],'focus'),
 b('focus','Fokus statt Feed','Mach Konzentration leichter, bevor du Willenskraft verlangst.',['Getting things done','Personal Care'],'clock','graphite','buddy',[
 s('*Räum die Startbahn frei*\n\nSchalte unnötige Benachrichtigungen stumm. Lege das Handy außer Griffweite, wenn du es für deine Aufgabe nicht brauchst. Schließe zwei Tabs, die nichts mit dem nächsten Schritt zu tun haben.\n\nÖffne nur das Dokument oder Werkzeug, mit dem du beginnen willst.'),
 s('*Reserviere einen kleinen Block*\n\nWähle zehn Minuten ungestörte Arbeit nach diesem Ritual und trage sie bei Bedarf in deinen Kalender ein. Leg einen Zettel für Gedanken bereit, die später dran sind.\n\nDu musst nicht den ganzen Tag kontrollieren. Diese zehn Minuten sind ein Anfang.')],'focus'),
 b('first-action','Erster echter Move','Planen war nett. Jetzt darf etwas entstehen.',['Getting things done','Kreativität'],'idea','lemon','text',[
 s('*Bau die kleinste erste Version*\n\nArbeite drei Minuten am ersten konkreten Schritt deiner Hauptaufgabe. Schreibe eine Rohfassung, rechne den ersten Ansatz oder skizziere drei Stichpunkte.\n\nNotiere hier anschließend, was tatsächlich entstanden ist und womit du weitermachst. Unfertig ist erlaubt. Nur vorgestellt zählt noch nicht.',3,'text')],'focus'),
 b('fresh','Frisch statt Scroll','Ein Pflege-Moment, bevor der Feed deine Aufmerksamkeit bekommt.',['Personal Care','Mindfulness'],'drop','peach','buddy',[
 s('*Erst du*\n\nLeg das Handy sicher zur Seite. Wasche dein Gesicht so, wie es für deine Haut angenehm und gewohnt ist, oder erledige einen kleinen Teil deiner üblichen Morgenpflege. Kein neues Produkt nötig.\n\nNimm Temperatur, Berührung und Geruch kurz wahr. Mach eine Sache nach der anderen.',2)],'sunrise'),
 b('posture','Haltung zeigen','Aufrichten ohne Militärkommando. Du brauchst keine perfekte Pose.',['Fitness','Personal Care'],'fitness','sand','buddy',[
 s('*Platz im Oberkörper*\n\nSteh bequem oder sitze auf einem stabilen Stuhl. Stell dir vor, der Scheitel zieht sanft nach oben. Lass die Schultern locker. Strecke beide Arme in einen angenehmen Bereich und senke sie wieder. Wiederhole fünfmal.',1,'none',true),
 s('*Locker in den Tag*\n\nGehe langsam durch den Raum oder verlagere im Sitzen dein Gewicht sanft nach links und rechts. Lass den Blick nach vorne wandern.\n\nWähle eine Position, in der du gut atmen kannst. Haltung ist Bewegung, kein Zustand, den du den ganzen Tag festhalten musst.',1,'none',true)]),
 b('soundtrack','Dein Soundtrack','Zwei Minuten mit Rhythmus. Tanztalent wird nicht kontrolliert.',['Personal Care','Kreativität'],'music','grape','text',[
 s('*Dein privater Opening-Track*\n\nHör auf den Rhythmus im Hintergrund. Tippe mit den Fingern mit, wiege dich im Sitzen oder beweg dich locker im Raum. Du kannst die Musik in der Lautstärke anpassen.\n\nWenn du heute Ruhe lieber magst, schalte sie aus und nimm zwei Minuten nur die Geräusche um dich herum wahr.',2,'none',true)],'flow'),
 b('kindness','Kleine gute Geste','Main Character Energy funktioniert auch mit anderen Menschen.',['Mindfulness','Personal Care'],'speech','copper','text',[
 s('*Wer fällt dir ein?*\n\nDenk an jemanden, dem eine ehrliche kleine Nachricht guttun könnte. Formuliere einen Satz: ein konkretes Danke, eine aufmerksame Nachfrage oder eine Erinnerung an etwas Schönes.\n\nSchreib ihn hier als Entwurf. Ob du ihn später verschickst, entscheidest du selbst. Keine Antwortpflicht, kein Networking-Move.',2,'text')]),
 b('world','Welt statt Feed','Ein kurzer Blick in die Welt, mit Quellen statt Endlos-Scrollen.',['Wissen'],'globe','blue','text',[
 s('Recherchiere bis zu drei relevante Entwicklungen aus Wissenschaft, Umwelt oder Technik aus den letzten sieben Tagen. Schreibe auf Deutsch höchstens 180 Wörter. Nenne pro Meldung das Ereignisdatum, erkläre die konkrete Neuerung und verlinke eine möglichst ursprüngliche Quelle. Trenne bestätigte Ergebnisse von Prognosen. Wenn es keine ausreichend belegten aktuellen Treffer gibt, sage das ausdrücklich. Erfinde keine positive Nachricht, um die Liste zu füllen.',2,'none',false,true)]),
 b('learn','Wissen snacken','Ein Konzept verstehen, statt zehn Überschriften zu sammeln.',['Wissen','Getting things done'],'book','petrol','buddy',[
 s('Erkläre auf Deutsch in höchstens 180 Wörtern, wie aktives Abrufen beim Lernen funktioniert. Recherchiere dazu verlässliche Fach- oder Hochschulquellen. Gib eine einfache Erklärung, ein konkretes Beispiel mit fünf Vokabeln und eine wichtige Grenze der Methode. Nenne die verwendeten Quellen. Versprich keine garantierten Lernerfolge und erfinde keine Zahlen.',2,'none',false,true),
 s('*Mach den Mini-Test*\n\nSchau kurz weg. Erkläre dir selbst in zwei Sätzen, was aktives Abrufen bedeutet und wie du es heute ausprobieren könntest.\n\nNotiere deine Erklärung aus dem Gedächtnis. Danach darfst du zurückschauen und eine Lücke ergänzen.',1,'text')]),
 b('ideas','Ideen ohne Filter','Erst Material produzieren. Der innere Kritiker hat später Schicht.',['Kreativität'],'idea','lime','text',[
 s('*Fünf Möglichkeiten, keine Jury*\n\nWähle eine kleine Frage: Wie könnte ich meine Pause gestalten? Wie starte ich das Projekt? Wie überrasche ich jemanden?\n\nSchreib fünf verschiedene Antworten. Eine darf unpraktisch sein, eine überraschend, eine sehr einfach. Noch nichts bewerten.',2,'text'),
 s('*Eine Idee bekommt Füße*\n\nWähle die Idee, die du am leichtesten testen kannst. Ergänze: „In zehn Minuten könnte ich …“\n\nBeschreibe ein kleines Experiment, kein fertiges Meisterwerk.',1,'text')]),
 b('explain','Sag’s auf den Punkt','Verstanden ist, was du mit eigenen Worten erklären kannst.',['Wissen','Kreativität'],'speech','stone','text',[
 s('*Deine 30-Sekunden-Version*\n\nNimm eine Sache, die du gerade gelernt oder bedacht hast. Erkläre sie als kurze Sprachnotiz: Was ist die Idee? Welches Beispiel macht sie greifbar? Welche Frage ist noch offen?\n\nSprich so, als würdest du es einem interessierten Freund erzählen. Fachwörter dürfen draußen bleiben.',2,'voice')])
];

const researchBlock=(slug,title,description,symbol,theme,query)=>b(slug,title,description,['Wissen'],symbol,theme,'buddy',[s(query,2,'none',false,true)]);
const news=[
 researchBlock('weather','Wetter','Dein Wetter heute. Mit einem Kleidungsvorschlag, der zum Tag passt.','sun','sunny','Recherchiere die Wettervorhersage für heute in {{ort}}. Nenne den Ort, den lokalen Tag, Temperatur morgens und nachmittags, Regenwahrscheinlichkeit und Wind. Nutze eine aktuelle Wetterquelle, keine historische Klimatabelle. Gib einen pragmatischen Kleidungsvorschlag für einen normalen Alltag draußen und drinnen, einschließlich Regenjacke oder Sonnenschutz nur wenn sinnvoll. Nenne die Quelle und deren Aktualität. Wenn für den konkreten Ort keine aktuelle Vorhersage auffindbar ist, sage das; erfinde keine Werte. Maximal 160 Wörter.'),
 researchBlock('stocks','Stocks','Was den Markt bewegt: Nachrichten und Kontext statt Kaufbefehle.','target','ocean','Recherchiere die wichtigsten neuen Entwicklungen an den Aktienmärkten seit dem letzten Handelstag. Schwerpunkt: {{aktien}}. Nenne höchstens drei Meldungen mit Ereignisdatum und belegter Quelle. Trenne Unternehmensnachrichten, Marktreaktionen und bloße Erwartungen. Verwende Kurse nur mit eindeutigem Zeitstempel; ohne verlässliche Kursquelle keine Zahlen. Kennzeichne geschlossene Börsen und Wochenenden. Keine Kauf- oder Verkaufsempfehlungen. Maximal 180 Wörter.'),
 researchBlock('world-news','Weltgeschehen','Die wichtigsten Entwicklungen, ohne dich im Nachrichtenstrom zu verlieren.','globe','blue','Recherchiere bis zu drei wichtige internationale Nachrichten aus den letzten 24 Stunden. Erkläre jeweils in zwei Sätzen, was passiert ist und weshalb es relevant ist. Nenne Ereignisdatum und Quellen. Bevorzuge seriöse Nachrichtenredaktionen und Primärquellen. Kennzeichne unbestätigte Angaben und laufende Entwicklungen, ohne sie als Tatsachen auszugeben. Kein Clickbait und keine künstliche Dramatisierung. Wenn die Suche keine ausreichend aktuellen Treffer liefert, benenne diese Grenze. Maximal 200 Wörter.'),
 researchBlock('local','Lokal informiert','Was in deiner Stadt heute tatsächlich wichtig oder nützlich ist.','compass','teal','Recherchiere für heute in {{ort}} relevante lokale Meldungen: Verkehr oder ÖPNV, öffentliche Hinweise und ein bis zwei interessante lokale Entwicklungen. Bevorzuge die Stadtverwaltung, örtliche Verkehrsbetriebe und lokale Nachrichtenredaktionen. Prüfe Gültigkeitszeitraum und exakten Ort. Keine alte Sperrung als aktuelle melden. Unterscheide heutige Hinweise von anstehenden Terminen; nenne genaue Daten, Quellen und bei Bedarf Stadtteil. Maximal 180 Wörter. Keine Treffer ausdrücklich sagen.'),
 researchBlock('tech','Tech Digest','AI, Robotik und Technologie: Substanz statt Launch-Hype.','idea','petrol','Recherchiere höchstens drei neue Entwicklungen in KI, Robotik oder Computertechnik aus den letzten 72 Stunden. Bevorzuge Originalankündigungen, veröffentlichte Forschung oder technische Dokumentation. Erkläre: Was ist neu, wer kann es schon nutzen und was ist noch Demo oder Ankündigung? Nenne Datum und Quelle. Bezeichne Herstellerbehauptungen ausdrücklich als solche. Keine erfundenen Benchmarks. Maximal 180 Wörter.'),
 researchBlock('good-news','Gute Nachrichten','Ein belegter Lichtblick. Kein Zwang, die Welt schönzureden.','heart','rose','Recherchiere bis zu zwei gut belegte positive Entwicklungen aus Wissenschaft, Umwelt oder Gesellschaft aus den letzten sieben Tagen. Erkläre konkret den Fortschritt und eine wichtige Grenze. Bevorzuge Forschungsinstitutionen, öffentliche Stellen und nachvollziehbare Berichte. Gib Ereignisdatum und Quellen an. Erfinde nichts, um eine positive Liste zu füllen; sage offen, wenn keine ausreichend aktuellen passenden Quellen vorliegen. Maximal 160 Wörter.'),
 researchBlock('culture','Kultur Kompass','Eine gute Idee für nach Feierabend, passend zu deiner Stadt.','music','grape','Finde in {{ort}} bis zu drei konkrete Kulturangebote für heute oder die kommenden sieben Tage: eine Ausstellung, ein Konzert oder eine andere öffentlich zugängliche Veranstaltung. Nutze Veranstalter- oder Veranstaltungsort-Seiten. Nenne Datum, Ort, Beginn und Preis nur wenn bestätigt; sonst kennzeichne unbekannte Angaben. Keine Verfügbarkeitsgarantie für Tickets. Verlinke die Originalquelle. Bevorzuge unterschiedliche und auch kostenlose Angebote. Maximal 180 Wörter.')
];
const meditation=b('meditation','Kurzmeditation','Drei Minuten, in denen du nichts optimieren musst.',['Mindfulness','Personal Care'],'leaf','sage','buddy',[
 {...s('*Drei Minuten bei dir*\n\nSetz dich bequem hin. Du kannst die Augen offen lassen. Spüre den Kontakt zum Stuhl oder Boden. Der Buddy begleitet dich mit kurzen Hinweisen und stillen Pausen. Du brauchst deinen Atem nicht zu verändern. Gedanken dürfen auftauchen; kehre freundlich zur nächsten Wahrnehmung zurück.',3,'none',true),guidance:{mode:'phases',cues:[
 {at:0,text:'Setz dich bequem hin. Lass die Augen offen oder schließe sie, wenn du magst. Spüre, wo dein Körper getragen wird.'},
 {at:30,text:'Nimm deinen Atem wahr, ohne ihn zu verändern. Wo spürst du die Bewegung am deutlichsten?'},
 {at:65,text:'Wenn Gedanken auftauchen, ist das okay. Nimm sie kurz wahr und kehre zum nächsten Atemzug zurück.'},
 {at:105,text:'Spüre deine Hände und Füße. Lass den Kiefer locker, soweit das angenehm ist.'},
 {at:150,text:'Nimm wieder die Geräusche im Raum wahr. Bewege langsam die Finger. Du kannst in deinem Tempo zurückkommen.'}
 ]}}
],'sunrise');
const chosen=['boot','mobility','technique','training','brain-dump','ground','good-move','priority','first-action','fresh','ideas','learn'].map(id=>foundationBlocks.find(b=>b.id==='wb-'+id));
chosen.find(b=>b.id==='wb-learn').title='Wissen snacken';
const boot=chosen.find(b=>b.id==='wb-boot');boot.steps[1].guidance={mode:'phases',cues:[{at:0,text:'Gehe locker auf der Stelle. Im Sitzen hebst du abwechselnd die Fersen.'},{at:30,text:'Kreise langsam die Schultern nach hinten. Lass die Arme anschließend locker ausschwingen.'},{at:50,text:'Werde langsamer. Spüre kurz nach. Dein Körper ist jetzt ein Stück wacher.'}]};
const mobility=chosen.find(b=>b.id==='wb-mobility');mobility.steps[0].guidance={mode:'repetitions',count:5,interval:8,start:12,intro:'Wir machen fünf langsame Schulterkreise nach hinten. Ich zähle mit. Bleib in deinem angenehmen Bewegungsbereich.'};
mobility.steps[1].guidance={mode:'phases',cues:[{at:0,text:'Halte dich bei Bedarf fest. Rolle langsam von den Fersen auf die Fußballen.'},{at:30,text:'Jetzt hebe abwechselnd ein Knie leicht an. Im Sitzen kannst du abwechselnd ein Bein strecken.'},{at:65,text:'Wechsle zurück zum Rollen der Füße. Lass dir Zeit.'},{at:100,text:'Lass die Bewegung ausklingen und finde einen stabilen Stand.'}]};
const technique=chosen.find(b=>b.id==='wb-technique');technique.steps.forEach((step,i)=>{step.guidance={mode:'repetitions',count:6,interval:7,start:12,intro:i?'Zweite Runde. Sechs kontrollierte Wiederholungen. Du kannst jederzeit eine Pause machen.':'Setz dich langsam auf den stabilen Stuhl und steh wieder auf. Nutze die Hände, wenn es hilft. Wir beginnen mit sechs Wiederholungen.'};});
export const CATALOG_BLOCKS=[...news,...chosen,meditation];
// Output and response types are editorial choices, using exactly the same step schema as the editor.
const lookup=id=>CATALOG_BLOCKS.find(block=>block.id==='wb-'+id);
const response=(id,text,input)=>{const block=lookup(id);block.steps.push({...s(text,1,input),id:block.id+'-'+(block.steps.length+1)});};
for(const block of CATALOG_BLOCKS)block.output=['brain-dump','priority','first-action','ideas'].includes(block.id.replace('wb-',''))?'text':'buddy';
lookup('stocks').contentRevision=2;
response('good-news','*Was bleibt hängen?*\n\nHalte in ein bis zwei Sätzen fest, welcher Fortschritt dir aufgefallen ist und welche Einschränkung wichtig bleibt. Dein eigener Gedanke zählt, nicht die perfekte Zusammenfassung.','text');
response('culture','*Eine Idee bekommt einen Termin*\n\nNotiere ein Angebot, das dich interessiert, und wann du es prüfen möchtest. Wenn nichts passt, schreib auf, worauf du stattdessen Lust hättest. Du musst nichts buchen.','text');
response('boot','*Dein Startbild*\n\nHalte deinen Start mit einem Foto fest: dein vorbereiteter Bewegungsplatz, deine Schuhe oder, wenn du möchtest, ein eigenes Fortschrittsfoto. Wähle später denselben Blickwinkel, wenn du vergleichen willst. Das Foto bleibt auf diesem Gerät.','photo');
response('mobility','*Bewegung festhalten*\n\nMach nach der Übung ein Foto deiner Matte, deines Bewegungsplatzes oder einer entspannten Position. Halte das Handy während der Bewegung nicht fest. Es geht um dein persönliches Protokoll, nicht um eine perfekte Pose.','photo');
response('technique','*Dein Trainingsprotokoll*\n\nWenn du möchtest, halte deinen Fortschritt mit einem Foto fest. Stell dich dafür erst sicher hin oder fotografiere deinen Trainingsaufbau. Kein Foto während einer Wiederholung. Vergleiche später mit dir selbst, nicht mit fremden Körpern.','photo');
lookup('training').steps[1]={...s('*Alles bereit*\n\nLege Schuhe, Matte oder ein anderes benötigtes Teil bereit und fotografiere deinen Aufbau. Überlege dir dabei deinen Plan B: Wenn das volle Training nicht klappt, welche kleine Alternative passt heute? Dein Foto ist die Erinnerung, dass der erste Schritt schon steht.',1,'photo'),id:'wb-training-2'};
lookup('ground').steps[1].input='voice';lookup('ground').steps[1].message.text+='\n\nSprich anschließend eine kurze Notiz: Welches Detail hast du wahrgenommen und wie fühlst du dich gerade? Ein Satz reicht.';
lookup('good-move').steps[0].input='voice';lookup('good-move').steps[0].message.text=lookup('good-move').steps[0].message.text.replace('Schreib:', 'Sprich eine kurze Notiz:');
response('fresh','*Bereit für dich*\n\nHalte eine kleine sichtbare Veränderung fest: deinen aufgeräumten Waschplatz, die bereitgelegten Sachen oder etwas anderes, das dir den Morgen leichter macht. Ein Foto reicht. Es muss kein Selfie sein.','photo');
response('meditation','*Kurz nachspüren*\n\nNimm eine kurze Sprachnotiz auf: Was fällt dir jetzt auf? Wie fühlt sich dein Körper an, welche Gedanken sind da? Auch „kein Unterschied“ ist eine ehrliche Antwort. Es gibt kein Meditationsergebnis abzuliefern.','voice');
// Keep written movement instructions and spoken cues consistent.
lookup('mobility').steps[0].message.text='Fünf langsame Schulterkreise nach hinten, im Stehen oder Sitzen. Bleibe in deinem angenehmen Bewegungsbereich. Der Buddy zählt den Beginn jeder Wiederholung; pro Kreis hast du acht Sekunden. Bei Schmerzen hörst du auf.';
lookup('mobility').steps[1].message.text='Halte dich bei Bedarf fest. Rolle von den Fersen auf die Fußballen. Nach 30 Sekunden hebst du abwechselnd ein Knie leicht an; im Sitzen streckst du abwechselnd ein Bein. Nach 65 Sekunden rollst du wieder die Füße, nach 100 Sekunden lässt du die Bewegung ausklingen.';
lookup('technique').steps[0].guidance.intro='Stabiler Stuhl: langsam hinsetzen und aufstehen. Hände helfen, alternativ Beine im Sitzen strecken. Bei Schmerzen stoppen.';
export const PREVIOUS_TEAM_BLOCKS=structuredClone(CATALOG_BLOCKS);
enrichExperiences(CATALOG_BLOCKS);
export const GUIDED_TEAM_BLOCKS=structuredClone(CATALOG_BLOCKS);
for(const block of CATALOG_BLOCKS){
 for(const step of block.steps){if(!step.guidance)continue;
  if(step.guidance.mode==='repetitions')step.message.text='*Zwei saubere Sätze*\n\nStabiler Stuhl an der Wand. Langsam hinsetzen und wieder aufstehen. Hände dürfen helfen. Alternative: sitzen bleiben und abwechselnd ein Bein strecken. Bei Schmerzen stoppen.\n\nSatz eins. Wir zählen ruhig: Eins … hinsetzen, aufstehen. Zwei … kontrolliert. Drei … weiteratmen. Vier … fester Stand. Fünf … ohne Eile. Sechs … geschafft.\n\nPause. Lockere die Beine. Atme bequem. Du kannst den Player für eine längere Pause anhalten.\n\nBereit für Satz zwei? Eins … langsam. Zwei … kontrolliert. Drei … bleib bei deiner Variante. Vier … weiteratmen. Fünf … fast da. Sechs … geschafft.\n\nLass die Bewegung ausklingen. Wie kontrolliert war deine letzte Wiederholung?';
  else step.message.text='*'+(step.message.text.match(/^\*([^*]+)\*/)?.[1]||'Dein Moment')+'*\n\n'+step.guidance.cues.map(c=>c.text).join('\n\n');
  delete step.guidance;
 }
 block.contentRevision=4;
}

const byId=new Map(CATALOG_BLOCKS.map(block=>[block.id,block]));
const ritual=(slug,title,description,ids)=>({id:'wb-ritual-'+slug,sourceId:'wb-ritual-'+slug,version:1,kind:'ritual',publisherId:TEAM_PUBLISHER,author:'Wakeup Buddy Team',title,description,theme:'lilac',blocks:ids.map(id=>byId.get('wb-'+id))});
export const CATALOG_RITUALS=[
 ritual('gym','Gym-Modus','Wetter checken, Körper wecken und kontrolliert in Bewegung kommen. Mit gezählten Wiederholungen und einem machbaren Trainingsplan.',['weather','boot','mobility','technique','training']),
 ritual('reset','Kopf auf Reset','Erst ankommen, dann den Kopf entlasten. Eine geführte Meditation und ein kleiner nächster Schritt, ohne Leistungsdruck.',['ground','meditation','brain-dump','good-move']),
 ritual('deliver','Heute wird geliefert','Wetter, Märkte und Tech auf dem Schirm. Danach eine klare Priorität und direkt der erste echte Schritt.',['weather','stocks','tech','priority','first-action']),
 ritual('main','Main Character','Bereit für deine Stadt: Wetter, lokale Hinweise, bewusste Pflege und eine Idee für nach Feierabend.',['weather','local','fresh','culture']),
 ritual('brain','Brain Gains','Weltgeschehen und Tech verstehen, aktiv lernen, einen Lichtblick mitnehmen und eigene Ideen entwickeln.',['world-news','tech','learn','good-news','ideas'])
];
